[project]
name = "aws-diagram-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awslabs-aws-diagram-mcp-server>=1.0.11",
    "streamlit>=1.50.0",
]
